import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Head from 'next/head'

import { UserProvider } from '@/contexts/UserContext'
import '@/styles/global.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Move.it',
  description: 'Generated by create next app',
}

export default function RootLayout ({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <UserProvider>
      <html lang="pt-BR">
        <Head>
          <link rel="shortcut icon" href="favicon.png" type="image/x-icon" />
        </Head>

        <body className={inter.className}>
          {children}
        </body>
      </html>
    </UserProvider>
  )
}
